# Generated by Django 3.0.3 on 2020-05-07 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200507_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='r_question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='app.Questions'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(default='enter Question', max_length=50),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(default='Enter Choice', max_length=50),
        ),
    ]
