# Generated by Django 3.0.3 on 2020-05-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200507_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='created_date',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='questions',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.CharField(default='tut', max_length=50, unique=True),
        ),
    ]
