# Generated by Django 3.0.3 on 2020-05-07 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200507_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='r_question',
        ),
        migrations.AddField(
            model_name='questions',
            name='ch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Choice'),
        ),
    ]
